In [ ]:
# imports 

[Fine Web](https://huggingface.co/spaces/HuggingFaceFW/blogpost-fineweb-v1) from Hugging Face.

In [1]:
import torch
import torch.nn as nn

# Batch Normalization (BatchNorm)
batch_norm = nn.BatchNorm1d(num_features=3)  # Normalisation sur chaque feature

# Layer Normalization (LayerNorm)
layer_norm = nn.LayerNorm(normalized_shape=3)  # Normalisation sur chaque exemple

# Simuler un batch de 4 échantillons, chacun avec 3 features
x = torch.tensor([[1.0, 2.0, 3.0], 
                  [4.0, 5.0, 6.0], 
                  [7.0, 8.0, 9.0], 
                  [10.0, 11.0, 12.0]], dtype=torch.float32)

print("Input Tensor:")
print(x)

Input Tensor:
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [2]:
# Appliquer BatchNorm (normalisation sur chaque feature)
x_bn = batch_norm(x)

# Appliquer LayerNorm (normalisation sur chaque exemple)
x_ln = layer_norm(x)

print("\nBatch Normalization Output:")
print(x_bn)

print("\nLayer Normalization Output:")
print(x_ln)



Batch Normalization Output:
tensor([[-1.3416, -1.3416, -1.3416],
        [-0.4472, -0.4472, -0.4472],
        [ 0.4472,  0.4472,  0.4472],
        [ 1.3416,  1.3416,  1.3416]], grad_fn=<NativeBatchNormBackward0>)

Layer Normalization Output:
tensor([[-1.2247,  0.0000,  1.2247],
        [-1.2247,  0.0000,  1.2247],
        [-1.2247,  0.0000,  1.2247],
        [-1.2247,  0.0000,  1.2247]], grad_fn=<NativeLayerNormBackward0>)
